{
 "title": "Kafka Streams performance",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "query": {
     "query": "label_values(kafka_stream_processor_node_record_e2e_latency_avg , env)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(kafka_stream_processor_node_record_e2e_latency_avg{env=\"$env\"} , instance)"
    }
   },
   {
    "name": "thread_id",
    "query": {
     "query": "label_values(kafka_stream_processor_node_record_e2e_latency_avg{env=\"$env\", instance=\"$instance\"}, thread_id)"
    }
   },
   {
    "name": "task_id",
    "query": {
     "query": "label_values(kafka_stream_processor_node_record_e2e_latency_avg{env=\"$env\", instance=\"$instance\", thread_id=\"$thread_id\"} , task_id)"
    }
   },
   {
    "name": "processor_node_id",
    "query": {
     "query": "label_values(kafka_stream_processor_node_record_e2e_latency_avg{env=\"$env\", instance=\"$instance\", thread_id=\"$thread_id\", task_id=~\"$task_id\"}, processor_node_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Records polled avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "records" } },
   "targets": [
    {
     "expr": "kafka_stream_thread_poll_records_avg{env=\"$env\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Poll per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kafka_stream_thread_poll_rate{env=\"$env\", instance=\"$instance\", thread_id=\"$thread_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Custom latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "custom_timer_seconds{quantile=\"0.5\", env=\"$env\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "kafka_stream_thread_process_rate{env=\"$env\", instance=\"$instance\", thread_id=\"$thread_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Operation latency avg per Thread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_stream_thread_commit_latency_avg{env=\"$env\", instance=\"$instance\", thread_id=\"$thread_id\"}",
     "legendFormat": "Commit"
    },
    {
     "expr": "kafka_stream_thread_poll_latency_avg{env=\"$env\", instance=\"$instance\", thread_id=\"$thread_id\"}",
     "legendFormat": "Poll"
    },
    {
     "expr": "kafka_stream_thread_process_latency_avg{env=\"$env\", instance=\"$instance\", thread_id=\"$thread_id\"}",
     "legendFormat": "Process"
    },
    {
     "expr": "kafka_stream_thread_punctuate_latency_avg{env=\"$env\", instance=\"$instance\", thread_id=\"$thread_id\"}",
     "legendFormat": "Punctuate"
    }
   ]
  },
  {
   "title": "e2e latency avg per Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (instance) (kafka_stream_processor_node_record_e2e_latency_avg{env=\"$env\", instance=\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Operation latency avg per Task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kafka_stream_task_process_latency_avg{env=\"$env\", instance=\"$instance\", thread_id=\"$thread_id\", task_id=~\"$task_id\"}",
     "legendFormat": "Process - {{task_id}}"
    },
    {
     "expr": "kafka_stream_task_punctuate_latency_avg{env=\"$env\", instance=\"$instance\", thread_id=\"$thread_id\",task_id=~\"$task_id\"}",
     "legendFormat": "Punctuate - {{task_id}}"
    },
    {
     "expr": "sum by (thread_id) (kafka_stream_task_process_latency_avg{env=\"$env\", instance=\"$instance\", thread_id=\"$thread_id\"})",
     "legendFormat": "Process - Sum"
    },
    {
     "expr": "sum by (thread_id) (kafka_stream_task_punctuate_latency_avg{env=\"$env\", instance=\"$instance\", thread_id=\"$thread_id\"})",
     "legendFormat": "Punctuate - Sum"
    }
   ]
  },
  {
   "title": "e2e latency avg per Thread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (instance, thread_id) (kafka_stream_processor_node_record_e2e_latency_avg{env=\"$env\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}} - {{thread_id}}"
    }
   ]
  },
  {
   "title": "Total Rebalancig",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "rebalances" } },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_rebalance_total{instance=\"$instance\"}",
     "legendFormat": "Total - {{instance}}"
    }
   ]
  },
  {
   "title": "e2e latency per Task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (instance, thread_id, task_id) (kafka_stream_processor_node_record_e2e_latency_avg{env=\"$env\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}} - {{thread_id}} - {{task_id}}"
    }
   ]
  },
  {
   "title": "e2e latency per Processor",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_stream_processor_node_record_e2e_latency_max{env=\"$env\", instance=\"$instance\", thread_id=\"$thread_id\"}",
     "legendFormat": "{{task_id}} - {{processor_node_id}}"
    }
   ]
  }
 ]
}